run_latest_update: true
cluster_name: siem
listen_address: 0.0.0.0
elastic_listen_port: 9200
discovery_nodes: ["10.0.1.4:9300","10.0.1.5:9300","10.0.1.6:9300"]
elastic_instances_url: ["http://10.0.1.4:9200","http://10.0.1.5:9200","http://10.0.1.6:9200"]
elastic_master_eligible_hosts: ["10.0.1.4","10.0.1.5","10.0.1.6"]
elastic_data_path: /var/lib/elasticsearch
elastic_log_path: /var/log/elasticsearch
logstash_data_path: /var/lib/logstash
logstash_log_path: /var/log/logstash
logstash_enable_xpack_monitoring: true
logstash_xpack_username: logstash_system
logstash_xpack_password: ktZ6WpqMWZbYW4ef
logstash_xpack_collection_interval: 30s
kibana_listen_port: 5601
kibana_elastic_req_timeout: 30000
kibana_elastic_shard_timeout: 30000
kibana_elastic_startup_timeout: 5000