---
- name: SIEM Elastic Stack Installation
  hosts: all
  become: yes

  roles:
    - ../roles/init
    - ../roles/repos
    - ../roles/elk-install
    - ../roles/rsyslog
  
  vars_files:
    - ../vars/main.yml
