---
- name: Instalando ferramentas básicas
  yum:
    name:
      - vim
      - net-tools
      - tcpdump
      - nmap
      - mtr
      - htop
      - git
      - python3-pip
    state: latest
    update_cache: yes
- name: Instala componente pip
  pip:
    name: passlib