---
- name: Import Elasticsearch PGP Key
  rpm_key:
    key: https://artifacts.elastic.co/GPG-KEY-elasticsearch
    fingerprint: 4609 5ACC 8548 582C 1A26 99A9 D27D 666C D88E 42B4
- name: Configure repository file
  copy:
    src: ../files/rpm-elasticsearch.repo
    dest: /etc/yum.repos.d/elasticsearch.repo