---
- name: Import Elasticsearch PGP Key
  rpm_key:
    key: https://artifacts.elastic.co/GPG-KEY-elasticsearch
- name: Configure repository file
  copy:
    src: ../files/rpm-elasticsearch.repo
    dest: /etc/yum.repos.d/elasticsearch.repo