---
- name: Import Elasticsearch PGP Key
  rpm_key:
    key: https://artifacts.elastic.co/GPG-KEY-elasticsearch
- name: Configure repository file
  copy:
    src: ../files/rpm-elasticsearch.repo
    dest: /etc/yum.repos.d/elasticsearch.repo
- name: Import Rsyslog PGP Key
  rpm_key:
    key: http://rpms.adiscon.com/RPM-GPG-KEY-Adiscon
- name: Configure Rsyslog repository file
  copy:
    src: ../files/rpm-rsyslog.repo
    dest: /etc/yum.repos.d/rsyslog.repo