---
- name: Instalando dependências de instalação do Docker
  package:
    name:
      - apt-transport-https
      - ca-certificates
      - curl
      - gnupg
      - lsb-release
    state: present
    update_cache: yes
- name: Importando Apt Key GPG do Docker
  apt_key:
    url: https://download.docker.com/linux/debian/gpg
    state: present
- name: Adiciona repositório do Docker
  apt_repository:
    repo: deb https://download.docker.com/linux/debian buster stable
    state: present