---
- name: Cria diretório para T-Pot
  file:
    path: /stor/tpot/
    state: directory
- name: Clonando projeto T-Pot via git
  git:
    repo: "https://github.com/telekom-security/tpotce.git"
    dest: /stor/tpot/
- name: Copiando arquivo de configuração
  template:
    src: /stor/tpot/tpotce/iso/installer/tpot.conf.dist
    dest: /root/tpot.conf
    owner: root
    group: root
    mode: 0644
- name: Instalando T-Pot - pode levar 15min à 30min
  command: /stor/tpot/tpotce/iso/installer/install.sh --type=auto --conf=/root/tpot.conf
- name: Remove arquivo de configuração do T-Pot
  file:
    path: /root/tpot.conf
    state: absent
- name: Ajusta unattended-upgrades para tomar ação padrão
  blockinfile:
    dest: /etc/apt/apt.conf.d/50unattended-upgrades
    block: |
      Dpkg::Options {
        "--force-confdef";
        "--force-confold";
      }