---
- name: Cria diretório para T-Pot
  file:
    path: /stor/tpot/
    state: directory
- name: Clonando projeto T-Pot via git
  git:
    repo: "https://github.com/telekom-security/tpotce.git"
    dest: /stor/tpot/
- name: Criando arquivo de configuração de instalação
  template:
    src: tpot.conf.j2
    dest: /root/tpot.conf
    owner: root
    group: root
    mode: 0644
- name: Instalando T-Pot - pode levar 15min à 30min
  command: /stor/tpot/iso/installer/install.sh --type=auto --conf=/root/tpot.conf
- name: Remove arquivo de configuração do T-Pot
  file:
    path: /root/tpot.conf
    state: absent
- name: Ajusta unattended-upgrades para tomar ação padrão
  blockinfile:
    dest: /etc/apt/apt.conf.d/50unattended-upgrades
    block: |
      Dpkg::Options {
        "--force-confdef";
        "--force-confold";
      }
- name: Altera senha do usuário admin
  user:
    name: admin
    password: "{{ admin_password|password_hash('sha512') }}"
    update_password: always
- name: Habilita ssh password auth
  lineinfile:
    dest: /etc/ssh/sshd_config
    regexp: '^#?PasswordAuthentication'
    line: 'PasswordAuthentication yes'
- name: Reiniciando sshd
  systemd:
    name: sshd
    state: restarted