---
- import_tasks: tasks/rpm.yml
  when: ansible_facts['os_family'] == "RedHat"
- import_tasks: tasks/deb.yml
  when: ansible_facts['os_family'] == "Debian"
- name: Configure UDP Syslog Reception
  lineinfile:
    path: /etc/rsyslog.conf
    regexp: '{{ item.re }}'
    line: '{{ item.line }}'
  with_items:
    - { re: '^#\$ModLoad imudp', line: '$ModLoad imudp' }
    - { re: '^#\$UDPServerRun 514', line: '$UDPServerRun 514' }
- name: Enable and restart Rsyslog
  service:
    name: rsyslog
    state: restarted
    enabled: yes